name: keep GitHub activity warm

on:
  schedule:
    - cron: '40 8 * * *'   # 11:40 Asia/Jerusalem == 08:40 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure committer
        run: |
          git config user.name "Guy Davidi (auto)"
          # Use your GitHub noreply or any verified email so the commit counts
          git config user.email "<YOUR_NOREPLY_OR_VERIFIED_EMAIL>"

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "chore: keepalive $(date -u +%F:%T)Z"
          git push

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "GitHub keepalive ✅ ($(date +'%Y-%m-%d %H:%M %Z'))"
          to: "guydav1111@gmail.com"
          from: "Guy's GitHub Bot <guydav1111@gmail.com>"
          body: |
            Keepalive commit pushed to ${{ github.repository }} on ${{ github.ref_name }}.
            Run: ${{ github.run_id }} • SHA: ${{ github.sha }}
