# .github/workflows/keepalive.yml
name: keep GitHub activity warm

on:
  schedule:
    - cron: '50 7 * * *'   # 11:40 Israel time == 08:40 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEFAULT_BRANCH || 'main' }}
          fetch-depth: 0
          persist-credentials: true

      - name: Resolve default branch (fallback)
        run: |
          set -euo pipefail
          git config --global safe.directory $(pwd)
          if [ -z "${DEFAULT_BRANCH:-}" ] || ! git rev-parse --verify "origin/${DEFAULT_BRANCH}" >/dev/null 2>&1; then
            DB=$(git remote show origin | awk '/HEAD branch:/ {print $NF}')
            echo "DEFAULT_BRANCH=$DB" >> $GITHUB_ENV
          else
            echo "DEFAULT_BRANCH=${DEFAULT_BRANCH}" >> $GITHUB_ENV
          fi

      - name: Configure committer
        run: |
          git config user.name "Guy Davidi (auto)"
          git config user.email "guy-davidi@users.noreply.github.com"

      - name: Make random empty commits (700–1000)
        run: |
          git checkout "${DEFAULT_BRANCH}"
          git pull --rebase origin "${DEFAULT_BRANCH}"
          COUNT=$((RANDOM % 301 + 700))  # random number 700–1000
          echo "Making $COUNT commits..."
          for i in $(seq 1 $COUNT); do
            git commit --allow-empty -m "chore: keepalive $i/$COUNT $(date -u +%F:%T)Z"
          done

      - name: Push all commits
        run: |
          git push origin HEAD:"${DEFAULT_BRANCH}"
